In [15]:
# hiring.csv This file contains hiring statics for a firm such as experience of candidate, his written test score and personal interview score. Based on these 3 factors, HR will decide the salary. Given this data, you need to build a machine learning model for HR department that can help them decide salaries for future candidates. 
# Using this predict salaries for following candidates
# 2 yr experience, 9 test score, 6 interview score
# 12 yr experience, 10 test score, 10 interview score


import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

val = pd.read_csv('hiring.csv')
val

,experience,test_score(out of 10),interview_score(out of 10),salary($)
0,NaN,8.0,9,50000
1,NaN,8.0,6,45000
2,five,6.0,7,60000
3,two,10.0,10,65000
4,seven,9.0,6,70000
5,three,7.0,10,62000
6,ten,NaN,7,72000
7,eleven,7.0,8,80000


In [29]:
#preprocess the data

from word2number import w2n
val['experience'] = val['experience'].fillna('zero')
val['experience']

0     0
1     0
2     5
3     2
4     7
5     3
6    10
7    11
Name: experience, dtype: int64

In [33]:
#in column use .apply(w2n.word_to_num)
#val['experience'] = val['experience'].apply(w2n.word_to_num)
#val

In [34]:
import math
med = val.experience.median()
for i in range(len(val)): 
    if val.experience[i]==0:
        val.experience[i] = med
val.experience

0     4
1     4
2     5
3     2
4     7
5     3
6    10
7    11
Name: experience, dtype: int64

In [36]:
median = val['test_score(out of 10)'].median()
val['test_score(out of 10)'] = val['test_score(out of 10)'].fillna(median)
val['test_score(out of 10)']

0     8.0
1     8.0
2     6.0
3    10.0
4     9.0
5     7.0
6     8.0
7     7.0
Name: test_score(out of 10), dtype: float64

In [37]:
val

,experience,test_score(out of 10),interview_score(out of 10),salary($)
0,4,8.0,9,50000
1,4,8.0,6,45000
2,5,6.0,7,60000
3,2,10.0,10,65000
4,7,9.0,6,70000
5,3,7.0,10,62000
6,10,8.0,7,72000
7,11,7.0,8,80000


In [38]:
# train the model

reg = linear_model.LinearRegression()
reg.fit(val[['experience', 'test_score(out of 10)', 'interview_score(out of 10)']], val['salary($)'])


LinearRegression()

In [39]:
reg.predict([[2, 9, 6]])

/Users/atulkumar/Library/Python/3.9/lib/python/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([46341.80249281])

In [41]:
reg.coef_

array([3390.87422644, 1803.45158198, 3184.69450013])

In [42]:
reg.intercept_

np.float64(4220.822801359725)

In [43]:
#manual solve
# y = mx+b
2*3390.87422644 + 9*1803.45158198 + 6*3184.69450013 + 4220.822801359725

46341.80249283972

In [44]:
reg.predict([[12, 10, 10]])

/Users/atulkumar/Library/Python/3.9/lib/python/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([94792.77433975])